### ISSUE TITLE
Version files are created without extension

### ISSUE THREAD

**Issue by pcav** [enricofer/layerVersion#2]
Therefore are not visible in the save and load dialogs.

**Comment by enricofer** [comment]
version files have a predefined ".qlv" extension. So dialogs filter only files with this extension, other files are not visible.

**Comment by enricofer** [comment]
In windows dialogs are right. In ubuntu are not.

**Comment by enricofer** [comment]
fixed https://github.com/enricofer/layerVersion/commit/954f7e65bdf8c3a8b27d52557707a562c6484d45
